variable "env" {}
variable "project_name" {}
variable "region" {}
variable "vpc_cidr_bolock" {}
variable "public_subnet_1_cidr_block" {}
variable "public_subnet_5_cidr_block" {}
variable "private_subnet_3_cidr_block" {}
variable "public_subnet_2_cidr_block" {}
variable "public_subnet_6_cidr_block" {}